platform: linux

image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks
    tag: latest

inputs:
- name: source
- name: env

run:
  path: source/ci/tasks/runIntegrationTestsAgainstTAS.sh

