groups:
- name: compile
  jobs:
  - claim-cf-deployment
  - test-and-build
  - test-against-tas-2-12
- name: deploy
  jobs:
  - deploy

resource_types:
- name: pcf-pool
  type: docker-image
  source:
    repository: cftoolsmiths/toolsmiths-envs-resource

- name: pivnet
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
  type: registry-image

resources:
# This is just so that we can trigger the job everytime there's a new TAS
# version.  It will download the tile... which is not quite nice in terms of
# execution time and resourse consumption. Maybe there's a better way.
- name: tas-for-vms-2-12
  type: pivnet
  source:
    api_token: ((pivnet.refresh_token))
    product_slug: elastic-runtime
    sort_by: semver
    product_version: 2\.12\..*

- name: source
  type: git
  source:
    uri: git@github.com:vmwarepivotallabs/cf-mgmt.git
    branch: main
    private_key: ((github.ssh_key))
    ignore_paths: ["README.md","docs/*"]

- name: draft-cfmgmt-resource
  type: github-release
  source:
    owner: vmware-tanzu-labs
    repository: cf-mgmt
    access_token: ((github.token))
    drafts: true

- name: releases
  type: github-release
  source:
    owner: vmware-tanzu-labs
    repository: cf-mgmt
    access_token: ((github.token))

- name: docker-registry
  type: docker-image
  source:
    repository: ((dockerhub.repository))
    username: ((dockerhub.username))
    password: ((dockerhub.password))
    tag: ((dockerhub.tag))

- name: cf-deployment-env
  icon: pool
  type: pcf-pool
  source:
    api_token: ((toolsmiths.api_token))
    hostname: environments.toolsmiths.cf-app.com
    pool_name: cf-deployment

- icon: pool
  name: tas-2-12-env
  source:
    api_token: ((toolsmiths.api_token))
    hostname: environments.toolsmiths.cf-app.com
    pool_name: us_2_12
  type: pcf-pool

- name: every-day
  type: time
  icon: timer-outline
  source:
    start: 9:00 AM
    stop: 10:00 PM
    days: [Monday, Tuesday, Wednesday, Thursday, Friday]

jobs:
- name: claim-cf-deployment
  plan:
  - get: every-day
    trigger: true
  - get: source
    trigger: true
  - put: cf-deployment-env
    params:
      action: claim

- name: test-and-build
  plan:
    - in_parallel:
      - get: every-day
        trigger: true
        passed: ['claim-cf-deployment']
      - get: source
        trigger: true
        passed: ['claim-cf-deployment']
      - get: cf-deployment-env
        passed: ['claim-cf-deployment']
        trigger: true
        version: every
    - task: unit-test
      file: source/ci/tasks/runTests.yml
    - load_var: pooled-env
      file: cf-deployment-env/metadata
      format: json
    - task: integration-test
      file: source/ci/tasks/runIntegrationTests.yml
      params:
        SYSTEM_DOMAIN: ((.:pooled-env.name)).cf-app.com
    - task: build
      file: source/ci/tasks/build.yml
    - put: draft-cfmgmt-resource
      params:
        name: compiled-output/name
        tag: compiled-output/tag
        globs:
        - compiled-output/cf-mgmt-linux
        - compiled-output/cf-mgmt-osx
        - compiled-output/cf-mgmt.exe
        - compiled-output/cf-mgmt-config-linux
        - compiled-output/cf-mgmt-config-osx
        - compiled-output/cf-mgmt-config.exe
    - put: cf-deployment-env
      params:
        action: unclaim
        env_file: cf-deployment-env/metadata

- name: test-against-tas-2-12
  plan:
    - in_parallel:
      - get: tas-for-vms-2-12
        trigger: true
      - get: source
        trigger: true
        resource: source
      - put: tas-2-12-env
        params:
          action: claim
    - task: integration-test
      file: source/ci/tasks/runIntegrationTestsAgainstTAS.yml
      input_mapping:
        env: tas-2-12-env
    - put: tas-2-12-env
      params:
        action: unclaim
        env_file: tas-2-12-env/metadata


- name: deploy
  plan:
    - in_parallel:
      - get: source
      - get: releases
        trigger: true
    - task: prepare
      file: source/ci/tasks/prepare.yml
    - put: docker-registry
      params:
        build: prepare-output
        tag_as_latest: true
        tag: prepare-output/version
